### PR TITLE
Bump to PHPStan Latte level 6

### PR DESCRIPTION
**Pull request by spaze**
Oh look this was easy 😅

Ref #141

### CODE REVIEW

**Comment by lulco** [comment]
Time for next level :D

In my case there are these checkpoints:
Level 2 - get it works
Level 5 - more errors
Level 6 - types everywhere
Level 8 - nullable 
Level 9 - mixed (unreachable because of ActiveRow)

**Comment by spaze** [comment]
Already exploring level 7. Got some 50 errors, some seem duplicated but fixing those is slow because I have to check whether it's me, you, or Latte? If it's not me, is it a bug, or is it me but just _holding it wrong_?

In most cases I can find a workaround, but guess that doesn't help you much :-)

**Comment by lulco** [comment]
If you are not sure, create issue :) we can check it too in some spare time. Sometimes it is phpstan itself and you just have to write your code the way to satisfy it.

**Comment by spaze** [comment]
Cool, thanks. Let me know if you think I create too one too many issues or they're 🐂💩 🤭

**Pull request merged**
