### PR TITLE
Bump PHPStan templates check to level 4

### PR DESCRIPTION
**Pull request by spaze**
Ref #141

### CODE REVIEW

**Comment by spaze** [comment]
@lulco I've now created some issues () because I don't know how to proceed:
- efabrica-team/phpstan-latte#387
- efabrica-team/phpstan-latte#388
- efabrica-team/phpstan-latte#389
- efabrica-team/phpstan-latte#390
- efabrica-team/phpstan-latte#391
If you have a second or two millions of them, any help is appreciated! :-)

**Comment by lulco** [comment]
Thank you. It's great we have this kind of (legacy) app for testing :) there are so many cases there we even didn't think about :) I have to admit that we probably have to rewrite some parts of extension and maybe also change some basic principles

**Comment by spaze** [comment]
Thanks, though I don't really consider this to be a legacy app :-)

**Comment by lulco** [comment]
OK sorry :) wrong words O:-)
It’s just not app I usually see or work with.
I usually use components for shared code, here includes are used.

**Comment by spaze** [comment]
Yeah, [including templates](https://latte.nette.org/en/template-inheritance#toc-printing-blocks) seemed like an easier tool for the job I was trying to do than [components](https://doc.nette.org/en/application/components) :-) Will look into them again though, to see if it would be worth a refactoring 💪

**Comment by lulco** [comment]
Maybe try first those smaller included templates mentioned in some other issue :)

**Comment by spaze** [comment]
Thanks, I'll see how far I can take it like this and then will see.

**Comment by spaze** [comment]
You were right @lulco. Even though using components means a bit more work I can now understand why it's worth it. Much better encapsulated and things like that. I was also able to work around #388.

**Comment by lulco** [comment]
Nice :) but from now your app is similar to mine, so you will probably find less edge cases :D 

Issue https://github.com/efabrica-team/phpstan-latte/issues/388 is still a thing and I will try to solve it, but it is not so simple as I thought.

Did you try level 5 already? O:-)

**Comment by spaze** [comment]
Edge cases? You mean unsupported features? 🤭 I till have some `{include ...}`s, I have not replaced all of them, just what was needed to resolve the current errors.

Agree, `{form $form}` is still an issue, I just found a way around it amd don't need it at the moment.

I have a level 5 issue which may be worht looking at, someday, will file it.

**Pull request merged**
