### PR TITLE
PHPStan latte

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by lulco** [comment]
@spaze two questions:
- do you push vendors?
- can you approve to run tests? O:-)

**Comment by spaze** [comment]
> * do you push vendors?

Yes

> * can you approve to run tests? O:-)

Yes :-)
And btw, you only need to run the PHP tests on pul requests (I've made tests to run on PRs in #64 now)

**Comment by lulco** [comment]
Thanks, can you check some errors? Select some presenter if it is correct or false positive. I don’t know the app, so not sure where to look at. You can ignore form fields now, it is in progress.

**Comment by spaze** [comment]
Looking at some of the errors now, these are the interesting ones. I'll create a separate comment for each file so you can link to it in issues if you want.

**Comment by spaze** [comment]
```
 ------ ----------------------------------------------------------------------- 
  Line   app/Admin/Presenters/templates/Emails/default.latte rendered from      
         MichalSpacekCz\Admin\Presenters\EmailsPresenter::default               
 ------ ----------------------------------------------------------------------- 
  33     Offset 0 on array{title: mixed} in isset() does not exist.             
  33     Result of && is always false.                                          
  63     Cannot access offset 'additional' on Nette\ComponentModel\IComponent.  
 ------ ----------------------------------------------------------------------- 
```
([link to the test output](https://github.com/spaze/michalspacek.cz/actions/runs/3850754254/jobs/6564378195#step:6:289))

Line 63 is form-related so I'll leave that out for now, but line 33 is this:
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Emails/default.latte#L33

This compiles to
```php
$ʟ_tmp = ['title' => $application->company];
echo Latte\Essential\Nodes\NAttrNode::attrs(isset($ʟ_tmp[0]) && is_array($ʟ_tmp[0]) ? $ʟ_tmp[0] : $ʟ_tmp, false) /* line 33 */;
```

The `isset($ʟ_tmp[0]) && is_array($ʟ_tmp[0]) ? $ʟ_tmp[0] : $ʟ_tmp` snippet is something I can't really influence or change in my code, at least I think it's something internal to Latte.

**Comment by spaze** [comment]
```
 ------ --------------------------------------------------------------------- 
  Line   app/Admin/Presenters/templates/Homepage/default.latte rendered from  
         MichalSpacekCz\Admin\Presenters\HomepagePresenter::default           
 ------ --------------------------------------------------------------------- 
  53     Variable $preliminaryDateSet might not be defined.                   
  53     Variable $preliminaryTotal might not be defined.                     
 ------ --------------------------------------------------------------------- 
```
([test output](https://github.com/spaze/michalspacek.cz/actions/runs/3850754254/jobs/6564378195#step:6:294))
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Homepage/default.latte#L53
and the code that creates the template vars:
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/HomepagePresenter.php#L57
(guess this could be written better but here we are 😅)

**Comment by spaze** [comment]
```
 ------ ----------------------------------------------------------------------- 
  Line   app/Admin/Presenters/templates/Interviews/default.latte rendered from  
         MichalSpacekCz\Admin\Presenters\InterviewsPresenter::interview         
         included in app/Admin/Presenters/templates/Interviews/interview.latte  
 ------ ----------------------------------------------------------------------- 
  1      Variable $item might not be defined.                                   
  2      Variable $item might not be defined.                                   
  3      Variable $item might not be defined.                                   
  4      Variable $item might not be defined.                                   
  5      Variable $item might not be defined.                                   
  11     Variable $form might not be defined.                                   
  37     Variable $interview on left side of ?? always exists and is not        
         nullable.                                                              
  39     Cannot access offset 'videoEmbed' on Nette\Forms\Container|false.      
  42     Cannot access offset 'sourceName' on Nette\Forms\Container|false.      
  45     Cannot access offset 'sourceHref' on Nette\Forms\Container|false.      
  48     Cannot access offset 'submit' on Nette\Forms\Container|false.          
  59     Variable $interviews might not be defined.                             
  64     Variable $interviews might not be defined.                             
 ------ ----------------------------------------------------------------------- 
```
([test output](https://github.com/spaze/michalspacek.cz/actions/runs/3850754254/jobs/6564378195#step:6:302))

Lines 1-5 (`Variable $item might not be defined.`)
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Interviews/default.latte#L1-L7
The `$item` var exists
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Interviews/default.latte#L64-L66
But I'd agree that it would probably be better passing it explicitly by `{include #itemInterview, item => $item}` so this seems fine

Line 37 (`Variable $interview on left side of ?? always exists and is not nullable.`)
The template is included in some other templates too and the variable might not exist when the template is rendered from some other presenter. This probably could also be written in a nicer way and I'd consider it a valid notice and would look into it.

Line 59, 64 (`Variable $interviews might not be defined.`)
Unless I'm looking at something else, I don't see `$interviews` on line 59:
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Interviews/default.latte#L56-L61
compiled to
```php
		echo '<div id="pridat-rozhovor">
	<p><a href="#pridat-rozhovor" class="open-container block">Přidat rozhovor</a></p>
	<div id="pridat-rozhovor-container" class="hidden">
';
		$this->renderBlock('interviewForm', ['form' => 'addInterview'] + get_defined_vars(), 'html') /* line 59 */;
		echo '	</div>
</div>
```

However on line 64:
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Interviews/default.latte#L64
it does exist as created in `renderDefault` here:
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/InterviewsPresenter.php#L32-L36

**Comment by spaze** [comment]
```
------ ---------------------------------------------------------------------- 
  Line   app/Admin/Presenters/templates/Trainings/default.latte rendered from  
         MichalSpacekCz\Admin\Presenters\HomepagePresenter::default included   
         in app/Admin/Presenters/templates/Homepage/default.latte              
 ------ ---------------------------------------------------------------------- 
  3      Variable $iterator might not be defined.                              
  4      Variable $application might not be defined.                           
  6      Variable $application might not be defined.                           
  7      Variable $application might not be defined.                           
  8      Variable $application might not be defined.                           
  10     Variable $application might not be defined.                           
  22     Parameter #2 $s of static method Latte\Essential\Filters::strip()     
         expects string, Latte\Runtime\Html|string|false given.                
  23     Access to an undefined property object::$price.                       
  34     Variable $trainings might not be defined.                             
  35     Variable $trainings might not be defined.                             
  36     Variable $upcomingIds in isset() always exists and is not nullable.   
  37     Variable $order might not be defined.                                 
  38     Variable $now in isset() always exists and is not nullable.           
  40     Variable $now in isset() always exists and is not nullable.           
  47     Variable $order might not be defined.                                 
  48     Variable $order might not be defined.                                 
  51     Variable $now in isset() always exists and is not nullable.           
  94     Variable $form might not be defined.                                  
  95     Variable $id might not be defined.                                    
  102    Parameter #1 $string of function rtrim expects string, string|false   
         given.                                                                
  103    Parameter #1 $string of function rtrim expects string, string|false   
         given.                                                                
  109    Parameter #1 $string of function rtrim expects string, string|false   
         given.                                                                
 ------ ---------------------------------------------------------------------- 
```
([test output](https://github.com/spaze/michalspacek.cz/actions/runs/3850754254/jobs/6564378195#step:6:431))

Line 22 (`Parameter #2 $s of static method Latte\Essential\Filters::strip() expects string, Latte\Runtime\Html|string|false given.`)
`$title` is created in the template with `{capture $title}`, not sure how to write it any other way, so I wouldn't consider this as mine issue 😊
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Trainings/default.latte#L11-L22

Line 102, 103, 109 (`Parameter #1 $string of function rtrim expects string, string|false given.`)
Seems to be related in `inputError`
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Trainings/default.latte#L102-L103
https://github.com/spaze/michalspacek.cz/blob/7ca6ab60db98df30db24a37b2ca0717de19673d5/site/app/Admin/Presenters/templates/Trainings/default.latte#L109

Those template snippets are compiled to this:
```php
		try {
			echo '<span class="error">';
			ob_start();
			try {
				echo LR\Filters::escapeHtmlText(end($this->global->formsStack)['start']->getError()) /* line 102 */;
			} finally {
				$ʟ_ifc[0] = rtrim(ob_get_flush()) === '';
			}
			echo '</span>';
		} finally {
			if ($ʟ_ifc[0] ?? null) {
				ob_end_clean();
			} else {
				echo ob_get_clean();
			}
		}
```
and `rtrim()` is in the inner `finally` block. I don't think I can do something with it in the template or the controller.

**Comment by spaze** [comment]
Enough for now 😅 not sure if this is the best way for you, let me know. Thanks!

**Comment by lulco** [comment]
Thank you very much! I'll check it. It's great you split that to single comments 👍 

I already create issue for assigning into array https://github.com/efabrica-team/phpstan-latte/issues/200. Never wrote it this way but it is probably valid, so I'll try to cover it.

Sharing templates is common issue. And I'm not sure how (and if) we solve that some variable is set only in some controls / presenters that use this template. Recommended way is to assign variable always in all controls / presenters using the same template and not use isset. Its's because we test template with context build from one control / presenter at the time so we don’t know about other controls / presenters

**Comment by spaze** [comment]
> Sharing templates is common issue. And I'm not sure how (and if) we solve that some variable is set only in some controls / presenters that use this template. Recommended way is to assign variable always in all controls / presenters using the same template and not use isset. Its's because we test template with context build from one control / presenter at the time so we don’t know about other controls / presenters

Yeah, that code is some 10 years old and I took a shortcut back then 😅 I'd write it differently today, I'd maybe create a class with properties with default values and pass that object instead. And maybe, with a little help from your extension, now is the right time to do something about it 💪

**Comment by lulco** [comment]
I've updated phpstan-latte extension, some errors should disappear, e.g. `Invalid identifier name ""` and assigning into array / list

**Comment by spaze** [comment]
Thanks for the PR & help @lulco! I've replaced this PR with #68, feel free to check it out too. I had to change some of my code so that the extension can find stuff - not sure if that's something that can be tuned in the extension, or if my code was that bad, probably the latter 😅

**Comment by lulco** [comment]
Well there are some edge cases which are not supported by extension, feel free to create issues if you think they are false positives. Som issues can be fixed by rewriting the code a little :)

**Comment by lulco** [comment]
Ah, and thank you for testing :)

**Pull request closed without merging**
