### PR TITLE
Try feature phpstanCommand if it make speed up

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by lulco** [comment]
Ok I'm not sure if it is faster :) the time is similar to other runs

**Comment by lulco** [comment]
@spaze please can you kill Infinite jobs from first commit? Because I can’t.

**Comment by spaze** [comment]
Seems they eventually got killed after 27 minutes 🤣https://github.com/spaze/michalspacek.cz/actions/runs/6054313232

**Comment by spaze** [comment]
GitHub Actions run time fluctuates quite a lot between runs, it can be 2 mins but also 3, or 1, for the same run, so it's very hard to benchmark something with Actions. But I've tried it running locally with the speedup, and I also get very similar results, something I'd even call a statistical error 😅 But I did just one run for each with, or without the feature (introduced in #429), in both cases with cache disabled. The result was around the reported 12% speed-up (sorry I don't have the exact number, I've closed my terminal, oops, it was around 5 mins which is quite slow in either case) But I think I've seen the PHPStan progress bar duplicated which makes sense if I correctly understand what it is doing, but it's still confusing. Could be probably hidden with some `phpstan` params but still. I don't feel like going this way at least not for now.

For me, a speed-up, an optimization, or any dirty-or-not tricks would be welcome!

**Pull request closed without merging**
